# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(verbose_name='Sentence')),
                ('textId', models.TextField(verbose_name='Text ID')),
                ('sentId', models.TextField(verbose_name='Sentence ID')),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('dutch_name', models.CharField(max_length=50)),
                ('machine_value', models.IntegerField(help_text='The actual numeric value stored in the database. Created automatically.')),
            ],
            options={
                'ordering': ['field', 'machine_value'],
            },
        ),
        migrations.CreateModel(
            name='HelpChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('searchable', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=50)),
                ('help_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.TextField(verbose_name='Part of speech')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Sorry, no help available for relation.name', verbose_name='Path from PP down')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Name for this situation')),
                ('preposition', models.TextField(blank=True, verbose_name='Preposition that must apply')),
                ('npType', models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for situation.npType', max_length=5, verbose_name='NP type')),
                ('penta', models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for situation.penta', max_length=5, verbose_name='Pentaset category')),
                ('action', models.CharField(choices=[('0', '-'), ('1', 'N/A')], default='0', help_text='Sorry, no help available for situation.action', max_length=5, verbose_name='Action to be taken')),
                ('antecedent', models.ForeignKey(blank=True, help_text='Sorry, no help available for situation.antecedent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_situation_antecedent', to='pentasit.Node')),
                ('example', models.ManyToManyField(to='pentasit.Example')),
                ('nodes', models.ManyToManyField(blank=True, to='pentasit.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Sorry, no help available for word', verbose_name='The word')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pentasit.Relation'),
        ),
        migrations.AddField(
            model_name='node',
            name='word',
            field=models.ManyToManyField(blank=True, to='pentasit.Word'),
        ),
    ]
