# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pentasit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='action',
            field=models.CharField(choices=[('1', 'Leave'), ('0', 'None')], default='0', help_text='Sorry, no help available for situation.action', max_length=5, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='npType',
            field=models.CharField(choices=[('1', 'DefNP'), ('4', 'DemNP'), ('2', 'IndefNP'), ('3', 'QuantNP')], default='0', help_text='Sorry, no help available for situation.npType', max_length=5, verbose_name='NP type'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='penta',
            field=models.CharField(choices=[('4', 'Assumed'), ('1', 'Identity'), ('3', 'Inert'), ('2', 'Inferred'), ('5', 'New')], default='0', help_text='Sorry, no help available for situation.penta', max_length=5, verbose_name='Ref cat'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='preposition',
            field=models.CharField(blank=True, max_length=20, verbose_name='Preposition'),
        ),
    ]
