# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pentasit', '0002_auto_20160708_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='pos',
            field=models.CharField(max_length=50, verbose_name='Part of speech'),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(help_text='Sorry, no help available for word', max_length=50, verbose_name='The word'),
        ),
    ]
