# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pentasit', '0004_auto_20160708_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'DefNP'), ('4', 'DemNP'), ('2', 'IndefNP'), ('3', 'QuantNP')], default='0', help_text='Sorry, no help available for situation.npType', max_length=5, verbose_name='NP type')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='other',
            field=models.CharField(blank=True, help_text='Sorry, no help available for other.name', max_length=100, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='example',
            name='sentId',
            field=models.CharField(max_length=70, verbose_name='Sentence ID'),
        ),
        migrations.AlterField(
            model_name='example',
            name='textId',
            field=models.CharField(max_length=70, verbose_name='Text ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='pos',
            field=models.CharField(blank=True, help_text='Sorry, no help available for pos.name', max_length=50, verbose_name='Part of speech'),
        ),
        migrations.AddField(
            model_name='node',
            name='npType',
            field=models.ManyToManyField(blank=True, to='pentasit.NpType'),
        ),
    ]
