# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pentasit', '0007_auto_20170306_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='npType',
        ),
        migrations.RemoveField(
            model_name='node',
            name='word',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='example',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='nodes',
        ),
        migrations.AlterField(
            model_name='nptype',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nptypes', to='pentasit.Node'),
        ),
        migrations.AlterField(
            model_name='word',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='pentasit.Node'),
        ),
    ]
